---
- hosts: mywebserver
  become: yes
  tasks:
    - name: i want to install the webserver on ubuntu
      apt:
       name: "{{mywebpackageforubuntu}}"
       state: present
      when: ansible_os_family =="Debian"

    - name: i want to install the webserver on ubuntu
      service:
       name: "{{mywebpackageforubuntu}}"
       state: started
      when: ansible_os_family =="Debian"

    - name: i want to install the webserver on Redhat
      yum:
        name: "{{mywebpackageforredhat}}"
        state: present
      when: ansible_os_family =="RedHat"

    - name: i want to start the webserver on Redhat
      service:
        name: "{{mywebpackageforredhat}}"
        state: started
      when: ansible_os_family =="RedHat"


    