---
- hosts: mywebserver
  become: yes
  tasks:
   - include_tasks: myfile.yml
   - name: i wnat to install webserver 
     apt:
      name: apache2
      state: present
      

   - name: i want to copy file into ansible nodes
     template: 
       src: myindex.j2
       dest: /var/www/html/index.html
       