---
- name: i want to create the tomcat group
  group:
    name: tomcat
    state: present 

- name: i want to create the tomcat group
  user:
    name: tomcat
    shell: /bin/false
    group: tomcat
    home:  /opt/tomcat
    state: present     
  