---
- name: download tomcat tar file
  get_url:
    url: https://downloads.apache.org/tomcat/tomcat-10/v10.0.22/bin/apache-tomcat-10.0.22.tar.gz
    dest: /home/ubuntu/apache-tomcat-10.0.22.tar.gz
    force_basic_auth: yes

- name: create directory
  file:
     path: /opt/tomcat
     state: directory

- name: extract tar file
  command:
    cmd: sudo tar xzvf /home/ubuntu/apache-tomcat-10.0.22.tar.gz -C /opt/tomcat --strip-components=1
    creates: /opt/tomcat/LICENSE