---
# tasks file for mywebrole
- name: install webserver
  apt:
   name: apache2
   state: present

- name: copy index file
  template:
    src: myindex.j2
    dest: /var/www/html/index.html 
  notify: restart webserver
   